title: Milim Kim
description: Korean Tutor
site_title: 'Learn Korean with Milim'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Miriam-81
blog_url: 
email: normalgem@hotmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/profile.png

# Google Analytics ID
google_analytics: 
