title: "Professional Korean Tutor | Milim Kim"
description: "Learn Korean online with Milim Kim. Offering online lessons via private Zoom links, as well as in-person 1-to-1 or group classes in the Liverpool area"
site_title: "Learn Korean with Milim | Online Korean Lessons"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Miriam-81
blog_url: 
email: normalgem@hotmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/Kim.png

# Google Analytics ID
google_analytics: G-4G5BRJ0YGF
